spring:
  application:
    name: securescope-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/securescope_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

security:
  jwt:
    secret: secure-scope-local-development-secret-key-change-before-production
    expiration-minutes: 120
